---
# Common variables
availability_zone: melbourne-qh2-uom
network: qh2-uom-internal
# instance_key_name: Muhammads-MBP
instance_key_name: comp90024-group19

# Volume
volumes:
  - vol_name: website-1
    vol_size: 10

# Security group
security_groups:
  - name: comp_ssh
    description: "COMP90024 security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: comp_http
    description: "COMP90024 security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: website-1
    image: 215f9775-483c-4e0a-b703-d21a5c966f2e # 	NeCTAR Ubuntu 18.04 LTS (Bionic) amd64 (with Docker)
    flavor: m3.small
    volumes: ["website-1"]
