- hosts: localhost
  vars_files:
    - variables/nectar.yml
  gather_facts: true

  roles:
    - role: common
    - role: images
    - role: volumes
    - role: security-group
    - role: instances
    - role: volume-snapshot
