- hosts: localhost
  vars_files:
    - variables/nectar.yml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volumes
    - role: openstack-security-group
    - role: openstack-instances
    - role: openstack-volume-snapshot
