---
# Set proxy

- name: Add proxy in /etc/environment
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      http_proxy=http://wwwproxy.unimelb.edu.au:8000/
      https_proxy=http://wwwproxy.unimelb.edu.au:8000/
      no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.nectar.org.au,.storage.unimeln.edu.au,.cloud.unimelb.edu.au

- name: Setup proxy for docker
  become: yes
  blockinfile:
    path: /etc/systemd/system/docker.service
    insertafter: \[Service\]
    block: |
      Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"

- name: Flush changes and restart docker
  become: yes
  systemd:
    daemon_reload: yes
    state: restarted
    name: docker

- name: Reboot a machine
  become: yes
  reboot:
    reboot_timeout: 3000

- name: Install vim
  become: yes
  apt:
    name: ["vim"]
    state: latest
    install_recommends: yes
    update_cache: yes
