---
- name: Setup cluster
  vars:
    node_count: "{{ ansible_play_hosts | length }}"
  tags: "couchdb"
  command: 'curl -X POST -H "Content-Type: application/json" http://{{ database_user }}:{{ database_password }}@127.0.0.1:5984/_cluster_setup -d ''{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "{{ database_user }}", "password": "{{ database_password }}", "port": 5984, "node_count": "{{ node_count }}"'''
# - name: Join to cluster
#   tags: "couchdb"
#   command: 'curl -X POST -H "Content-Type: application/json" http://{{ database_user }}:{{ database_password }}@<setup-coordination-node>:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 5984, "node_count": "3", "remote_node": "<remote-node-ip>", "remote_current_user": "<remote-node-username>", "remote_current_password": "<remote-node-password>" }'''

# - name: Join to cluster
#   tags: "couchdb"
#   command curl -X POST -H "Content-Type: application/json" http://admin:password@<setup-coordination-node>:5984/_cluster_setup -d '{"action": "add_node", "host":"<remote-node-ip>", "port": <remote-node-port>, "username": "admin", "password":"password"}'
