- hosts: nectar
  vars_files:
    - host_vars/harvester.yml
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/comp90024-group19.pem
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  gather_facts: true

  roles:
    - role: install-docker
    - role: run-harvester
